### ISSUE TITLE
Better text color for progress bar in dark mode

### ISSUE THREAD

**Issue by ihubgit** [Jacalz/rymdport#115]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/Jacalz/rymdport/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

Hi while being in dark mode, all text is white, except the one on the progess bar which remains black and thus doesn't help for readability.

### Describe the solution you'd like to see.

White text on the progress bar.

**Comment by Jacalz** [comment]
This is technically a problem over at https://github.com/fyne-io/fyne. I'll see what I can do about this and keep it open in the meantime.

I have a vague recollection that we changed the colour because it improved contrast. However, I do admit that it does look a little out of place and with poor contrast.

**Comment by Jacalz** [comment]
Yeah, it is indeed a change that we made on Fyne a while back because it gives better contrast in the light theme. However, I do agree that it does look odd with the text not matching. I'll open an issue in Fyne for discussing how it can be handled

**Comment by Jacalz** [comment]
Closing in favour of https://github.com/fyne-io/fyne/issues/4845 being tracked upstream.
