### ISSUE TITLE
Support for webwormhole

### ISSUE THREAD

**Issue by VarLad** [Jacalz/rymdport#80]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/Jacalz/rymdport/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

While wormhole is nice for sending from one device to other on the local network, webwormhole is an alternative to send data across the internet using p2p.

### Describe the solution you'd like to see.

It would be nice if rymdport could support webwormhole alongside wormhole as well. 
Its written in Go as well (repo link here: https://github.com/saljam/webwormhole ) and for the UI, it can be the same as what rymdport provides for magic wormhole.
Which means:
1. Generate word code/QR code
2. Progress bar for sending/receiving

**Comment by Jacalz** [comment]
Thanks for opening this feature request. I have thought a bit about it and I am not quite sure if it is something that I want to implement.

Adding a new protocol to support seems like it would confuse people and convolute the code quite a bit. If anything, I'd prefer if `webwormhole` supported the `magic-wormhole` protocol instead of implementing a new one. The latter seems like more of a standard to me.

I'm sorry that this probably isn't what you want to hear. However, I do have plans to compile to web assembly and run Rymdport in the browser some time in the future. There is a lot of work needed to get that working though so it would probably happen a year or two in the future, if not later. It is not a short term solution unfortunately.
